language: node_js
node_js:
- '0.11'
- '0.10'
before_install:
- npm install -g ngn
before_script:
- npm link
- npm link ngn
notifications:
  hipchat:
    rooms:
      secure: 3sOZJCvD9AEX4f5m4LRVGfLaZA776OKoBIzz+lf7dhoUnb3xlgZgCv2ZoXgqO0+hVWicalWbdDfrqgftLxktFxrrp7ybF0oaLTSr7zI9NCTKRHr/vXb6jeRr0I36xpOhmRgfghydR48qHoizSqcUX86dCoxu8yyWUBS0k9xvKHk=
    template:
    - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}'
    format: html
